const { GAME_STATUS } = require('runandrisk-common/const')

export const VIEWS = {
    HOME: 'HOME',
    CONNECTING: 'CONNECTING',
    CONNECTION_ERROR: 'CONNECTION_ERROR',
    WAITING_PLAYERS: GAME_STATUS.WAITING_PLAYERS,
    PLAYING: GAME_STATUS.PLAYING
}

export const VIEWS_PLAYING = {
    NORMAL: 'NORMAL',
    SEND_UNITS: 'SEND_UNITS',
    LEADERS: 'LEADERS'
}
