const { GAME_STATUS } = require('runandrisk-common/const')

const VIEWS = {
    HOME: 'HOME',
    CONNECTING: 'CONNECTING',
    CONNECTION_ERROR: 'CONNECTION_ERROR',
    WAITING_PLAYERS: GAME_STATUS.WAITING_PLAYERS,
    PLAYING: GAME_STATUS.PLAYING
}

export default VIEWS
